FactoryBot.define do
  factory :machine_learning_job do
    association :user, factory: :user
    script { "script.py" }
    started_at { Time.current - 1.hour }
    finished_at { Time.current }

    trait :working do
      finished_at { nil }
    end

    trait :with_error do
      error { "Error description" }
    end
  end

  factory :ml_summary_comment do
    body { "Summary comment generated by Machine Learning" }

    trait :debate do
      association :commentable
      commentable_type { "Debate" }
    end

    trait :proposal do
      association :commentable
      commentable_type { "Proposal" }
    end

    trait :investment do
      association :commentable
      commentable_type { "Budget::Investment" }
    end
  end
end
